my_string = input('Введите слово для того, что бы узнать количество букв: ')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.strip())
print(my_string[0])
print(my_string[4])